### ISSUE TITLE
Include functionality in frontend forms (not only in the admin backend)

### ISSUE THREAD

**Issue by caumons** [danirus/django-wysihtml5#10]
If I'm not wrong, this django app is intended to add rich text functionality to admin and that's great because it's really simple to setup.

But I'd like to be able to add this functionality also to the forms that I'm using in the frontend. Is there any way to do so currently, or is it a new enhancement to be done? In case it's a new feature it'd be great to add it to this library!

Thanks! :)

**Comment by danirus** [comment]
I do fully agree. 
Yes, it's a new feature.
Are you on your way to implement it? :)

**Comment by danirus** [comment]
I'll do this as it's a must in the app.

**Comment by danirus** [comment]
Sorry Caumons. I didn't look at the code before I answered. And I'm wrong. 
The functionality you need is there. You just have to use a `Wysihtml5TextField` like in the Article model of the demo project. To render the css and js files the widget needs the form.media in your template.

Based on the example demo project and the model Article:

```
from django.forms import ModelForm
from demo.articles.models import Article

class ArticleForm(ModelForm):
    class Meta:
        model = Article
```

In your views.py:

```
def edit(request, article_id):
    try:
        article = Article.objects.get(pk=article_id)
        form = ArticleForm(instance=Article.objects.get(pk=1))
    except Article.DoesNotExist:
        return render(request, 'article_doesnotexist.html')
    else:
        return render(request, 'edit_article.html', {'form': form})
```

And in your 'edit_article.html' template add `{{ form.media }}` to render the css and js files before you render the form with `{{ form }}`.

**Comment by caumons** [comment]
Hi danirus!

Thanks for your fast response. Using the {{ form.media }} in head section worked fine!

I think that it'd be really good to properly document this, or else other developers may think that this library is only for backend purposes and frontend is not supported.

One more question, is it possible to set the bar to actually look like the "original" one in http://jhollingworth.github.io/bootstrap-wysihtml5/? I mean if is it possible by changing some CSS file or whatever.

Thanks for your job and for sharing it with us! :)

**Comment by danirus** [comment]
Yes, you can do that. Create a subclass from `wysihtml5.widgets.Wysihtml5AdminTextareaWidget` and declare a `Media` class attribute in your own using the files defined in bootstrap-wysihtml5. It would be nice to extend the demo project (in `django-wysihtml5/example/demo`) with such functionality. Maybe adding a couple of new urls in the demo.articles app, to allow create and update articles.

The example looks awesome. I'll try to get some free time to extend the demo project.

**Comment by danirus** [comment]
I just added bootstrap-wysihtml5 to the demo project. See the file boot `twitter_bootstrap.py`, there's a specific widget class there to make use of bootstrap-wysihtml5 library. Also the forms.py file implements the ModelForm rendered in http://localhost:8000/articles/new

If you need several Wysihtml5 editors in the same page with formsets look at the `render_js_delay_widget` method of Wysihtml5TextareaWidget and implement a similar method for Wysihtml5BootstrapWidget.

Hope it helps! ;)

**Comment by caumons** [comment]
Thanks for your job! I'll try it during this week. I think this commit will improve a lot the look and feel :)
