### ISSUE TITLE
pip install is broken

### ISSUE THREAD

**Issue by magnetic-pi** [danirus/django-wysihtml5#11]
I am trying to use the pip installer however there is an error in the:

username@twingeeks:~$ sudo pip install django-wysihtml5
Downloading/unpacking django-wysihtml5
  Downloading django-wysihtml5-1.1b1.linux-x86_64.tar.gz (179Kb): 179Kb downloaded
  Running setup.py egg_info for package django-wysihtml5
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/home/winterfell/build/django-wysihtml5/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/home/winterfell/build/django-wysihtml5/setup.py'

**Comment by danirus** [comment]
It's already fixed in PyPI.
Thank you!

**Comment by magnetic-pi** [comment]
I just confirmed that it's working. Thanks for the amazing response!
