### ISSUE TITLE
Focusing on Element

### ISSUE THREAD

**Issue by magnetic-pi** [danirus/django-wysihtml5#13]
Is is possible to focus in on the textarea for the wysihtml5 editor? I'm trying to add some validation to check for text input, however I an not able to focus in on the body to verify that text. Essentially I am trying to do somehting similar to this:

$('#id_textfield').keyup(checkSubmit);

However I do not have an ID, NAME, or way of using the class to get the element.  Do you have any idea's of the best way to approach this? This is what is available:

```
<body marginwidth="0" marginheight="0" contenteditable="true" class="vLargeTextField wysihtml5-editor" spellcheck="true" style="background-color: rgb(255, 255, 255); color: rgb(85, 85, 85); cursor: auto; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 20px; letter-spacing: normal; text-align: start; text-decoration: none; text-indent: 0px; text-rendering: auto; word-break: normal; word-wrap: break-word; word-spacing: 0px;">asdfasdfasdfasdfadsfasdf<br>asdf<br><br><br><div>asdf</div></body>
```

**Comment by danirus** [comment]
Watch out, the textarea is being replaced by the wysihtml5 sandbox. You will need to get access to the iframe and then to the body.

**Comment by magnetic-pi** [comment]
So running your demo try the following in a chrome developer console:

```
frameBody = $(".wysihtml5-sandbox").contents().find("body")
```

I even tried:

```
frameBody = $(".wysihtml5-sandbox").contents().find("body").val()
```

That did not return the text as expected. All it returns is empty quotes " ". Also, I have multiple fields(4 to be exact), that all have the same sandbox. configuration. I am trying to think of ways to reference them separately.

**Comment by danirus** [comment]
Look at what Matyas says [here](http://stackoverflow.com/questions/10739237/insert-html-programatically-in-wysihtml5-editor/13868608#13868608). I think that's pretty much what you are looking for, right?
