### ISSUE TITLE
NodeJS Config

### ISSUE THREAD

**Issue by magnetic-pi** [danirus/django-wysihtml5#17]
I have been really digging this module. I am stuck in one place. I am trying to figure out how to name the <body vLargeTextField wysihtml5-editor placeholder>

```
#document
<html>
<body marginwidth="0" marginheight="0" contenteditable="true" class="vLargeTextField wysihtml5-editor placeholder" spellcheck="true" style="background-color: rgb(255, 255, 255); color: rgb(85, 85, 85); cursor: auto; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 13.63636302947998px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 20px; letter-spacing: normal; text-align: start; text-decoration: none; text-indent: 0px; text-rendering: auto; word-break: normal; word-wrap: break-word; word-spacing: 0px;">testing text</body>
<html>
```

I have multiple editors on my screen. I would be great if I could name the body, something like editor1, editor2, etc... 

```
#document
<html>
<body name="editor1" marginwidth="0" marginheight="0" contenteditable="true" class="vLargeTextField wysihtml5-editor placeholder" spellcheck="true" style="background-color: rgb(255, 255, 255); color: rgb(85, 85, 85); cursor: auto; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 13.63636302947998px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 20px; letter-spacing: normal; text-align: start; text-decoration: none; text-indent: 0px; text-rendering: auto; word-break: normal; word-wrap: break-word; word-spacing: 0px;">testing text</body>
<html>
```

The reason I would like this functionality is so that I could do something with javascript where I can update the textarea on the fly and vice versa. 

```
 $("#textarea2").keyup(function () {
 $('[name="editor1"]').contents().find('body').html($('#textarea2').val());
});
```

I could also do vice versa. Unfortunately all the bodies are exactly the same. So I am having one hell of a time grabbing the .html from from the body that is generated in the iframe.

Essentially I am trying to hook in the textarea into [sharejs](http://sharejs.org/), which would allow people to collaborate through this editor in near real time. Once I get is set up, I'd love to give you the docs on how I set it up. Its pretty straight forward. :)

Cheers,
Jon

**Comment by danirus** [comment]
This is not an issue of django-wysihtml5.
