### ISSUE TITLE
Add way to set additional Editor options

### ISSUE THREAD

**Issue by jonashaag** [danirus/django-wysihtml5#5]
For instance I want to set `useLineBreaks: false`

**Comment by danirus** [comment]
Thanks for the report.
Just resolved and fixed.

Use the setting WYSIHTML5_EDITOR in settings.py, like:

```
WYSIHTML5_EDITOR = {
    'useLineBreaks': 'false'
}
```

**Comment by jonashaag** [comment]
I love you! Three bugs fixed within a few hours. Incredible.

**Comment by danirus** [comment]
I was waiting in the airport when I saw your messages. It was much enjoyable than shopping. :-)
