### ISSUE TITLE
KeyError with createLink and insertImage -> False

### ISSUE THREAD

**Issue by alican** [danirus/django-wysihtml5#7]
I just try to set some of the Toolbar buttons in WYSIHTML5_TOOLBAR to False. Its all fine, except for "createLink" and "insertImage". 
If i try to set one of this to "active":False, than the page raise a KeyError.
Is it a bug or maybe am I doing something wrong?

**Comment by danirus** [comment]
You are doing it right. It's a bug.
Thanks for reporting!
